"""
Django settings for flocs project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import dj_database_url
import os
try:
    import flocs.private_settings as private_settings
except ImportError:
    import logging
    logger = logging.getLogger(__name__)
    logger.error('Using default private settings! Security is compromised ' +
                 'and OAuth logins are not available!')
    import flocs.private_settings_template as private_settings

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXPORTED_DATA_DIR = os.path.join(BASE_DIR, 'exported-data')
FRONTEND_DIR = os.path.join(BASE_DIR, 'frontend')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = private_settings.SECRET_KEY

ON_STAGING = os.getenv('ON_STAGING', "False") == "True"
ON_PRODUCTION = os.getenv('ON_AL', "False") == "True" and not ON_STAGING
DEVELOPMENT = not ON_STAGING and not ON_PRODUCTION
DEBUG = (not ON_PRODUCTION) or (os.getenv('DJANGO_DEBUG', "False") == "True")
ALLOWED_HOSTS = [
    '.thran.cz'
]

if ON_PRODUCTION or ON_STAGING:
    FRONTEND_BUILD_DIR = os.path.join(BASE_DIR, 'frontend', 'production-build')
else:
    FRONTEND_BUILD_DIR = os.path.join(BASE_DIR, 'frontend',
                                      'development-build')


# Application definition

INSTALLED_APPS = (
    'django.contrib.contenttypes',
    'modeltranslation',  # must be before django.contrib.admin
    'grappelli.dashboard',  # must be before django.contrib.admin
    'grappelli',  # must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'import_export',
    'lazysignup',
    'social.apps.django_app.default',  # OAuth
    # our apps
    'common',
    'blocks',
    'concepts',
    'tasks',
    'feedback',
    'practice',
    'stats',
    'flocs',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'flocs.aspects.localization.LocalizationMiddleware',
)

ROOT_URLCONF = 'flocs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # frontend home directory (where to search for index.html)
        'DIRS': [FRONTEND_BUILD_DIR],

        # allow for fallback index.html in flocs/templates/
        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flocs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(default='sqlite:///' +
                                      os.path.join(BASE_DIR, 'db.sqlite3'))
}


# Internationalization
USE_I18N = True
USE_L10N = True
USE_TZ = False
# TIME_ZONE = 'UTC'
LANGUAGES = [
    ('cs', 'Czech'),
    ('en', 'English')
]
if ON_PRODUCTION:
    LANGUAGE_DOMAINS = {
        'cs': 'flocs.thran.cz',
        'en': 'en.flocs.thran.cz',
    }
elif ON_STAGING:
    LANGUAGE_DOMAINS = {
        'cs': 'staging.flocs.thran.cz',
        'en': 'en.staging.flocs.thran.cz',
    }
else:
    LANGUAGE_DOMAINS = {
        'cs': 'localhost:8000',
        'en': 'en.localhost:8000',
    }
LANGUAGE_CODE = 'cs'  # fallback language
MODELTRANSLATION_DEFAULT_LANGUAGE = 'en'
MODELTRANSLATION_TRANSLATION_FILES = (
    'tasks.models.translation',
    'blocks.models.translation',
    'concepts.models.translation',
)

# Grappelli
GRAPPELLI_INDEX_DASHBOARD = 'flocs.dashboard.CustomIndexDashboard'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(FRONTEND_BUILD_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, '../static')


AUTHENTICATION_BACKENDS = (
  'django.contrib.auth.backends.ModelBackend',
  'lazysignup.backends.LazySignupBackend',
  'social.backends.facebook.FacebookOAuth2',
  'social.backends.google.GoogleOAuth2',
)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = private_settings.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = private_settings.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET

SOCIAL_AUTH_FACEBOOK_KEY = private_settings.SOCIAL_AUTH_FACEBOOK_KEY
SOCIAL_AUTH_FACEBOOK_SECRET = private_settings.SOCIAL_AUTH_FACEBOOK_SECRET
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
# SOCIAL_AUTH_USER_MODEL = 'django.contrib.auth.models.User'
SOCIAL_AUTH_SANITIZE_REDIRECTS = True

# http://stackoverflow.com/questions/22005841/is-not-json-serializable-django-social-auth-facebook-login
# SECRET_KEY MUST remain secret
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'

SOCIAL_AUTH_PIPELINE = (
    'social.pipeline.social_auth.social_details',
    'social.pipeline.social_auth.social_uid',
    'social.pipeline.social_auth.auth_allowed',
    'user.pipeline.remove_current_user',
    'social.pipeline.social_auth.social_user',
    'social.pipeline.user.get_username',
    'social.pipeline.user.create_user',
    'social.pipeline.social_auth.associate_user',
    'social.pipeline.social_auth.load_extra_data',
    'social.pipeline.user.user_details',
    'user.pipeline.manual_login',
)

# --------------------------------------------------------------------------
# Email
# --------------------------------------------------------------------------
EMAIL_HOST = 'localhost'
EMAIL_PORT = 25
EMAIL_SUBJECT_PREFIX = '[flocs]'
EMAIL_ADMINS = ['adaptive-programming@googlegroups.com']
SERVER_EMAIL = 'error-reporting@flocs.thran.cz'
ADMINS = (('Errors', 'adaptive-programming-errors@googlegroups.com'),)
if DEVELOPMENT:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --------------------------------------------------------------------------
# Logging
# --------------------------------------------------------------------------
LOGGING_DIR = os.getenv('LOGGING_DIR', "logs")
LOGGING = {
    'version': 1,
    'formatters': {
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(message)s'
        },
        'brief': {
            'format': '%(message)s'
        },
        'long-messages': {
            'format': '[%(asctime)s] %(message)s----------'
        },
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s %(module)s : ' +
                      '"%(message)s" in %(filename)s:%(lineno)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'practice-file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGGING_DIR + '/practice.log',
            'formatter': 'verbose'
        },
        'feedback-file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGGING_DIR + '/feedback.log',
            'formatter': 'long-messages'
        },
        'requests-file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGGING_DIR + '/requests.log',
            'formatter': 'simple'
        },
        'mail-admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler',
        }
    },
    'loggers': {
        'feedback': {
            'handlers': ['feedback-file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'practice': {
            'handlers': ['practice-file'],
            'level': 'DEBUG',
            'propagate': True
            },
        'django.request': {
            'handlers': ['requests-file', 'mail-admins'],
            'level': 'DEBUG',
            'propagate': True
        },
    }
}
